
#################################################
# INFRA Playbooks: portainer
# Source: 
#################################################
---
- hosts: swarm_managers
  gather_facts: no
  become: true
  vars:  
    portainer_dir: "/var/data/portainer"
  vars_files:
    - ./vars.env.yml
  tasks:
    ###
    # GENERAL Setup
    ###
    - name: Creates directory portainer
      file:
        path: "{{ portainer_dir }}"
        state: directory

    - name: Copy compose files to remote server
      copy:
        src: "{{ item }}"
        dest: "{{ portainer_dir }}"
      with_fileglob:
        - "{{ playbook_dir }}/docker-compose.*"
      tags:
        - general_setup
        - redeploy

    ###
    # Start Container
    ###
    - name: Remove stack
      docker_stack:
        name: portainer
        state: absent

    - name: Start portainer Stack
      docker_stack:
        state: present
        name: portainer
        compose: 
        - "{{ portainer_dir }}/docker-compose.yml"
        - "{{ portainer_dir }}/docker-compose.caddy.yml"
      environment:
        PORTAINER_DOMAIN: "{{PORTAINER_DOMAIN}}"
      tags:
        - redeploy