version: "3.7"

services:
  docker-registry:
    image: registry:2
    ports:
      - 5000:5000
    networks:
      - docker_swarm_private
    volumes:
      - registery_data:/var/lib/registry
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any

networks:
  docker_swarm_private:
    external: true

volumes:
  registery_data: {}