
#################################################
# INFRA Playbooks: Caddy
# Source: 
#################################################
---
- hosts: swarm_managers
  gather_facts: no
  become: true
  vars:  
    caddy_dir: "/var/data/caddy"
  vars_files:
    - ./vars.env.yml
  vars_prompt:
    - name: admin_password
      prompt: What is your password?
  tasks:
    ###
    # GENERAL Setup
    ###
    - name: Creates directory caddy
      file:
        path: "{{ caddy_dir }}"
        state: directory

    - name: Creates directory jwt
      file:
        path: "{{ caddy_dir }}/jwt"
        state: directory

    - name: Copy compose files to remote server
      copy:
        src: "{{ item }}"
        dest: "{{ caddy_dir }}"
      with_fileglob:
        - "{{ playbook_dir }}/docker-compose.*"
        - "{{ playbook_dir }}/Dockerfile.*"
      tags:
        - general_setup
        - redeploy

    - name: Create Caddyfile
      template:
        src: "templates/Caddyfile.j2"
        dest: "{{ caddy_dir }}/Caddyfile"
        mode: 0644

    - name: Create JWT signature token
      openssh_keypair:
        path: "{{ caddy_dir }}/jwt/access_token"

    - name: Create User static file
      template:
        src: "templates/users.json.j2"
        dest: "{{ caddy_dir }}/users.json"
        mode: 0644
    ###
    # Start Container
    ###
    - name: Remove stack
      docker_stack:
        name: caddy
        state: absent

    - name: Start Caddy Stack
      docker_stack:
        state: present
        name: caddy
        compose: 
        - "{{ caddy_dir }}/docker-compose.yml"
      environment:
        DOMAIN: "{{domain}}"
      tags:
        - redeploy